services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agrolav-sql
    hostname: boekhouding
    env_file:
      - hub/.env
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - "C:/SQLBackups:/var/opt/mssql/backup"